updated configuration data

diff --git a/deploy/action.yml b/deploy/action.yml
--- a/deploy/action.yml
+++ b/deploy/action.yml
@@ -55,7 +55,12 @@ runs:
           my_services="${my_services// /}"
           echo selected Services="${my_services}"
           mkdir -p /tmp/workspace/${{ github.run_id }}
-          wget -q -O "/tmp/workspace/${{ github.run_id }}/deploy.sh" https://github.com/sepia-innovations/sepia-devops-templates/configuration-data/raw/master/deploy.sh && echo "Download successful." || echo "Download failed."
+          wget -q -O "/tmp/workspace/${{ github.run_id }}/deploy.sh" https://github.com/sepia-innovations/sepia-devops-templates/blob/master/configuration-data/deploy.sh
+          # Check for download errors (exit code != 0)
+          if [[ $? -ne 0 ]]; then
+            echo "Error: Failed to download deploy.sh"
+            exit 1
+          fi
           chmod +x /tmp/workspace/${{ github.run_id }}/deploy.sh
           /tmp/workspace/${{ github.run_id }}/deploy.sh ${{ inputs.composedir }} ${my_services} ${{ inputs.newtag }}
           echo "Cleaning temporary workspace"
